on: 
  push:
    branches:
    - master
  workflow_dispatch:
name: Deploy FTP 🚀
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server }}
        port: ${{ secrets.ftp_port }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_dir }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          Symphony-tuto.md
          docker-compose*.yml
          .vscode/
